var hierarchy =
[
    [ "_WDIR", "struct___w_d_i_r.html", null ],
    [ "_wdirent", "struct__wdirent.html", null ],
    [ "lg::cudnn::Activation", "classlg_1_1cudnn_1_1_activation.html", null ],
    [ "Bitmap", "class_bitmap.html", null ],
    [ "lg::cudnn::Convolution", "classlg_1_1cudnn_1_1_convolution.html", null ],
    [ "lg::Cost", "classlg_1_1_cost.html", null ],
    [ "lg::CUDA_Tensor< T >", "classlg_1_1_c_u_d_a___tensor.html", null ],
    [ "DIR", "struct_d_i_r.html", null ],
    [ "dirent", "structdirent.html", null ],
    [ "lg::cudnn::Dropout", "classlg_1_1cudnn_1_1_dropout.html", null ],
    [ "lg::IOData", "classlg_1_1_i_o_data.html", null ],
    [ "lg::linear_regression", "classlg_1_1linear__regression.html", null ],
    [ "lg::logistic_regression", "classlg_1_1logistic__regression.html", null ],
    [ "MNIST_binary_loader", "class_m_n_i_s_t__binary__loader.html", null ],
    [ "lg::Neural_Network", "classlg_1_1_neural___network.html", null ],
    [ "lg::Node_Network", "classlg_1_1_node___network.html", null ],
    [ "lg::Operation", "classlg_1_1_operation.html", [
      [ "lg::Addition", "classlg_1_1_addition.html", null ],
      [ "lg::Autoencoder", "classlg_1_1_autoencoder.html", null ],
      [ "lg::Averagepooling", "classlg_1_1_averagepooling.html", null ],
      [ "lg::CapsulesDense", "classlg_1_1_capsules_dense.html", null ],
      [ "lg::Concatenate", "classlg_1_1_concatenate.html", null ],
      [ "lg::Convolution", "classlg_1_1_convolution.html", null ],
      [ "lg::Dropout", "classlg_1_1_dropout.html", null ],
      [ "lg::Linear", "classlg_1_1_linear.html", null ],
      [ "lg::Linear_Freeze", "classlg_1_1_linear___freeze.html", null ],
      [ "lg::Maxpooling", "classlg_1_1_maxpooling.html", null ],
      [ "lg::Normalization", "classlg_1_1_normalization.html", null ],
      [ "lg::Partial", "classlg_1_1_partial.html", null ],
      [ "lg::Recurrent", "classlg_1_1_recurrent.html", null ],
      [ "lg::Relu", "classlg_1_1_relu.html", null ],
      [ "lg::ResidualBlock", "classlg_1_1_residual_block.html", null ],
      [ "lg::Selu", "classlg_1_1_selu.html", null ],
      [ "lg::Sigmoid", "classlg_1_1_sigmoid.html", null ],
      [ "lg::Softmax", "classlg_1_1_softmax.html", null ],
      [ "lg::Tanh", "classlg_1_1_tanh.html", null ],
      [ "lg::Variable", "classlg_1_1_variable.html", null ]
    ] ],
    [ "lg::Optimizer", "classlg_1_1_optimizer.html", [
      [ "lg::DFA_Optimizer", "classlg_1_1_d_f_a___optimizer.html", null ],
      [ "lg::SGD_Optimizer", "classlg_1_1_s_g_d___optimizer.html", null ]
    ] ],
    [ "lg::Point", "classlg_1_1_point.html", null ],
    [ "lg::cudnn::Pooling", "classlg_1_1cudnn_1_1_pooling.html", null ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", null ],
    [ "lg::Tensor< T >", "classlg_1_1_tensor.html", null ],
    [ "lg::Tensor< float >", "classlg_1_1_tensor.html", null ],
    [ "lg::Tensor< int >", "classlg_1_1_tensor.html", null ],
    [ "lg::cudnn::TensorDescription", "classlg_1_1cudnn_1_1_tensor_description.html", null ]
];