var namespacelg =
[
    [ "cudnn", "namespacelg_1_1cudnn.html", "namespacelg_1_1cudnn" ],
    [ "Addition", "classlg_1_1_addition.html", "classlg_1_1_addition" ],
    [ "Autoencoder", "classlg_1_1_autoencoder.html", "classlg_1_1_autoencoder" ],
    [ "Averagepooling", "classlg_1_1_averagepooling.html", "classlg_1_1_averagepooling" ],
    [ "CapsulesDense", "classlg_1_1_capsules_dense.html", "classlg_1_1_capsules_dense" ],
    [ "Concatenate", "classlg_1_1_concatenate.html", "classlg_1_1_concatenate" ],
    [ "Convolution", "classlg_1_1_convolution.html", "classlg_1_1_convolution" ],
    [ "Cost", "classlg_1_1_cost.html", "classlg_1_1_cost" ],
    [ "CUDA_Tensor", "classlg_1_1_c_u_d_a___tensor.html", "classlg_1_1_c_u_d_a___tensor" ],
    [ "DFA_Optimizer", "classlg_1_1_d_f_a___optimizer.html", "classlg_1_1_d_f_a___optimizer" ],
    [ "Dropout", "classlg_1_1_dropout.html", "classlg_1_1_dropout" ],
    [ "IOData", "classlg_1_1_i_o_data.html", "classlg_1_1_i_o_data" ],
    [ "Linear", "classlg_1_1_linear.html", "classlg_1_1_linear" ],
    [ "Linear_Freeze", "classlg_1_1_linear___freeze.html", "classlg_1_1_linear___freeze" ],
    [ "linear_regression", "classlg_1_1linear__regression.html", "classlg_1_1linear__regression" ],
    [ "logistic_regression", "classlg_1_1logistic__regression.html", "classlg_1_1logistic__regression" ],
    [ "Maxpooling", "classlg_1_1_maxpooling.html", "classlg_1_1_maxpooling" ],
    [ "Neural_Network", "classlg_1_1_neural___network.html", "classlg_1_1_neural___network" ],
    [ "Node_Network", "classlg_1_1_node___network.html", "classlg_1_1_node___network" ],
    [ "Normalization", "classlg_1_1_normalization.html", "classlg_1_1_normalization" ],
    [ "Operation", "classlg_1_1_operation.html", "classlg_1_1_operation" ],
    [ "Optimizer", "classlg_1_1_optimizer.html", "classlg_1_1_optimizer" ],
    [ "Partial", "classlg_1_1_partial.html", "classlg_1_1_partial" ],
    [ "Point", "classlg_1_1_point.html", "classlg_1_1_point" ],
    [ "Recurrent", "classlg_1_1_recurrent.html", "classlg_1_1_recurrent" ],
    [ "Relu", "classlg_1_1_relu.html", "classlg_1_1_relu" ],
    [ "ResidualBlock", "classlg_1_1_residual_block.html", "classlg_1_1_residual_block" ],
    [ "Selu", "classlg_1_1_selu.html", "classlg_1_1_selu" ],
    [ "SGD_Optimizer", "classlg_1_1_s_g_d___optimizer.html", "classlg_1_1_s_g_d___optimizer" ],
    [ "Sigmoid", "classlg_1_1_sigmoid.html", "classlg_1_1_sigmoid" ],
    [ "Softmax", "classlg_1_1_softmax.html", "classlg_1_1_softmax" ],
    [ "Tanh", "classlg_1_1_tanh.html", "classlg_1_1_tanh" ],
    [ "Tensor", "classlg_1_1_tensor.html", "classlg_1_1_tensor" ],
    [ "Variable", "classlg_1_1_variable.html", "classlg_1_1_variable" ]
];